sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi


script:
  # Run just unit tests first -- if they fail we never spend the time building the environment for integration tests
  - composer unit-tests

  # Run integration tests
  - composer wp-tests

after_sucess:
  # Run coverage
  - vendor/bin/phpunit --coverage-clover=coverage.xml
